### ISSUE TITLE
fix tests failing with `Other element would receive the click`

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1090]
see https://github.com/owncloud/phoenix/pull/1042#issuecomment-489596961

```
 Element <#new-file-menu-btn> was visible after 31 milliseconds.
 Error while running .clickElement() protocol action: element click intercepted: Element <button class="oc-button uk-button-primary" id="new-file-menu-btn" aria-expanded="false">...</button> is not clickable at point (813, 90). Other element would receive the click: <div uk-dialog="{bgclose: false, escclose: false}" class="uk-modal-dialog uk-modal-body">...</div>

    ✖ failed
      Error while running "click" command: this.reporter.registerTestError is not a function
      TypeError: Error while running "click" command: this.reporter.registerTestError is not a function
          at transport.locateElement.then.then.catch.result (/var/www/owncloud/phoenix/node_modules/nightwatch/lib/api-loader/element-command.js:138:25)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:189:7)
    And the user deletes folder "my-empty-folder" using the webUI
    - skipped
    Then as "user1" folder "my-other-empty-folder" should exist
    - skipped
    And folder "my-other-empty-folder" should be listed on the webUI
    - skipped
    But as "user1" folder "my-empty-folder" should not exist
    - skipped
    And folder "my-empty-folder" should not be listed on the webUI
    - skipped
```

**Comment by paurakhsharma** [comment]
Looking at the test log I saw this error message:
`Warning: More than one element (2) found for <Element [name=@loadingIndicator]> with selector: "//*[contains(@class, "oc-loader")]". Only the first one will be used.`

Since we are using `waitForElementNotPresent('@loadingIndicator')`,
at some point there are more than one `oc-loadder` but `waitForElementNotPresent()`
only waits for one of them to disappear (probably the first one it finds) due to which the element
which we were waiting to disappear is still there and preventing the click to happen.

Hopefully only waiting for the specific loading indicator, in this case waiting for folder-creation-loading-indicator should solve our problem.
