### ISSUE TITLE
TUS folder upload issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#3458]
Run the following Phoenix acceptance tests against OCIS:

- tests/acceptance/features/webUIUpload/upload.feature:19

For some reason it seems that only the first file is uploaded, not sure why the second one isn't.

**Comment by PVince81** [comment]
```
1) Scenario: simple upload of a folder that does not exist before # tests/acceptance/features/webUIUpload/upload.feature:19
   ✔ Before # tests/acceptance/setup.js:28
   ✔ Before # tests/acceptance/setup.js:32
   ✔ Before # tests/acceptance/setup.js:36
   ✔ Before # tests/acceptance/setup.js:46
   ✔ Before # tests/acceptance/setup.js:68
   ✔ Before # tests/acceptance/setup.js:75
   ✔ Before # tests/acceptance/stepDefinitions/filesContext.js:15
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:191
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:230
   ✔ Given user "user1" has been created with default attributes # tests/acceptance/stepDefinitions/provisioningContext.js:126
   ✔ And user "user1" has logged in using the webUI # tests/acceptance/stepDefinitions/loginContext.js:63
   ✔ When the user uploads a folder containing the following files in separate sub-folders using the webUI: # tests/acceptance/stepDefinitions/filesContext.js:256                                                                                                            
       | lorem.txt     |
       | new-lorem.txt |
   ✔ Then no message should be displayed on the webUI # tests/acceptance/stepDefinitions/generalContext.js:83
   ✔ And the last uploaded folder should be listed on the webUI # tests/acceptance/stepDefinitions/filesContext.js:355
   ✔ And as "user1" the last uploaded folder should exist # tests/acceptance/stepDefinitions/webdavContext.js:62
   ✖ And as "user1" the last uploaded folder should contain the following files inside the sub-folders: # tests/acceptance/stepDefinitions/webdavContext.js:66                                                                                                                
       | new-lorem.txt |
       | lorem.txt     |
       AssertionError [ERR_ASSERTION]: Could not find following files inside sub-folders of the session folder
       new-lorem.txt,lorem.txt
           + expected - actual

           -2
           +0
       
           at _callee$ (/home/vincent/Private/Work/workspace/phoenix/tests/acceptance/stepDefinitions/webdavContext.js:89:12)
           at tryCatch (/home/vincent/Private/Work/workspace/phoenix/node_modules/regenerator-runtime/runtime.js:45:40)
           at Generator.invoke [as _invoke] (/home/vincent/Private/Work/workspace/phoenix/node_modules/regenerator-runtime/runtime.js:274:22)
           at Generator.prototype.(anonymous function) [as next] (/home/vincent/Private/Work/workspace/phoenix/node_modules/regenerator-runtime/runtime.js:97:21)
           at asyncGeneratorStep (/home/vincent/Private/Work/workspace/phoenix/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
           at _next (/home/vincent/Private/Work/workspace/phoenix/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
           at process._tickCallback (internal/process/next_tick.js:68:7)
   ✔ After # tests/acceptance/stepDefinitions/provisioningContext.js:200
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:235
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:215
   ✔ After # tests/acceptance/setup.js:110
   ✔ After # tests/acceptance/setup.js:106
   ✔ After # tests/acceptance/setup.js:102
   ✔ After # tests/acceptance/setup.js:95
   ✔ After # tests/acceptance/setup.js:86
   ✔ After # tests/acceptance/setup.js:54
```

**Comment by PVince81** [comment]
I checked the logs and actually new-lorem.txt got uploaded but there is no trace of lorem.txt.

also strange that the test result says 0 entries when I saw one entry in the folder which was "new-lorem.txt"

**Comment by PVince81** [comment]
okay, so something is stuck:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/277525/82311159-9ffd3500-99c5-11ea-93b4-16366ae02e6a.png">

seems the `tus` library is not loaded/initialized in all code paths. weird

**Comment by PVince81** [comment]
seems unrelated, I had an env issue, retrying...

**Comment by PVince81** [comment]
okay, I see: the test code is sending a Depth header with a value of 2, hoping to get the sub-sub-folder values. But the ocdav service is strict.
According to the spec, only "0", "1" and "infinity" are acceptable values: https://tools.ietf.org/html/rfc4918#section-10.2

Raised https://github.com/owncloud/ocis-reva/issues/212 to fix the depth header there and add some validation

**Comment by PVince81** [comment]
At first I tried to fix the test to do propfinds recursively but the parsing was too cumbersome, so I ended up simply implemented depth-infinity in OCIS: https://github.com/cs3org/reva/pull/758

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/phoenix/pull/3480
