### ISSUE TITLE
Dtrace errors when running acceptance-tests locally

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3942]
When running acceptance tests locally like this `yarn acceptance-tests tests/acceptance/features/webUIFiles/download.feature` I get the following result:

```console
yarn run v1.22.4
$ cucumber-js --require-module @babel/register --require-module @babel/polyfill --require tests/acceptance/setup.js --require tests/acceptance/stepDefinitions --format node_modules/cucumber-pretty -t "${TEST_TAGS:-not @skip and not @skipOnOC10}"
Error: Cannot find module './build/Release/DTraceProviderBindings'
Require stack:
- /Users/bene/Code/owncloud/phoenix/node_modules/dtrace-provider/dtrace-provider.js
- /Users/bene/Code/owncloud/phoenix/node_modules/bunyan/lib/bunyan.js
- /Users/bene/Code/owncloud/phoenix/node_modules/ldap/lib/index.js
- /Users/bene/Code/owncloud/phoenix/tests/acceptance/helpers/ldapHelper.js
- /Users/bene/Code/owncloud/phoenix/tests/acceptance/setup.js
- /Users/bene/Code/owncloud/phoenix/node_modules/cucumber/lib/cli/index.js
- /Users/bene/Code/owncloud/phoenix/node_modules/cucumber/lib/cli/run.js
- /Users/bene/Code/owncloud/phoenix/node_modules/cucumber/bin/cucumber-js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/bene/Code/owncloud/phoenix/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/Users/bene/Code/owncloud/phoenix/node_modules/cucumber/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (/Users/bene/Code/owncloud/phoenix/node_modules/cucumber/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/bene/Code/owncloud/phoenix/node_modules/bunyan/lib/bunyan.js:35:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/Users/bene/Code/owncloud/phoenix/node_modules/cucumber/node_modules/pirates/lib/index.js:99:24) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/bene/Code/owncloud/phoenix/node_modules/dtrace-provider/dtrace-provider.js',
    '/Users/bene/Code/owncloud/phoenix/node_modules/bunyan/lib/bunyan.js',
    '/Users/bene/Code/owncloud/phoenix/node_modules/ldap/lib/index.js',
    '/Users/bene/Code/owncloud/phoenix/tests/acceptance/helpers/ldapHelper.js',
    '/Users/bene/Code/owncloud/phoenix/tests/acceptance/setup.js',
    '/Users/bene/Code/owncloud/phoenix/node_modules/cucumber/lib/cli/index.js',
    '/Users/bene/Code/owncloud/phoenix/node_modules/cucumber/lib/cli/run.js',
    '/Users/bene/Code/owncloud/phoenix/node_modules/cucumber/bin/cucumber-js'
  ]
}
```

Is there some step involved to generate such a bindings file?
Trying with:
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```
```
node --version
v12.18.3
```
```
yarn --version
1.22.4
```
```
npm --version (although npm is not called directly)
6.14.6
```
```
node-gyp --version
v7.1.0
```

It looks like it is not required - acceptance tests are running successfully. But still, it looks wrong to me... any help/clarification is appreciated.

**Comment by kulmann** [comment]
Anyone else having this kind of errors? @individual-it

**Comment by swoichha** [comment]
I ran the same test `yarn acceptance-tests tests/acceptance/features/webUIFiles/download.feature` in current master and the tests runs successfully. I didn't get any results that you have mentioned here https://github.com/owncloud/phoenix/issues/3942#issue-677823886

**Comment by swoichha** [comment]
@LukasHirt could it be a MAC problem

**Comment by LukasHirt** [comment]
> could it be a MAC problem

Yep, likely a Mac issue https://github.com/trentm/node-bunyan/issues/525#issuecomment-319836630 I am getting the same errors.

**Comment by LukasHirt** [comment]
Some additional comments - https://github.com/yarnpkg/yarn/issues/1915#issuecomment-287283390

**Comment by kulmann** [comment]
Thanks to both of you for looking into it! Tests are running successfully on my machine as well, so I will ignore this logs for now.
