### ISSUE TITLE
Intermittent fail of tests/acceptance/features/webUIFiles/versions.feature:14

### ISSUE THREAD

**Issue by phil-davis** [owncloud/phoenix#4301]
I have seen this twice today in OCIS testing:
https://drone.owncloud.com/owncloud/ocis/1365/37/7
```
2) Scenario: upload new file with same name to see if different versions are shown (attempt 1, retried) # tests/acceptance/features/webUIFiles/versions.feature:14
   ✔ Before # tests/acceptance/setup.js:28
   ✔ Before # tests/acceptance/setup.js:32
   ✔ Before # tests/acceptance/setup.js:36
   ✔ Before # tests/acceptance/setup.js:46
   ✔ Before # tests/acceptance/setup.js:68
   ✔ Before # tests/acceptance/setup.js:75
   ✔ Before # tests/acceptance/stepDefinitions/filesContext.js:18
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:234
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:273
   ✔ Given these users have been created with default attributes: # tests/acceptance/stepDefinitions/provisioningContext.js:199
       | username |
       | user0    |
       | user1    |
   ✔ Given user "user0" has logged in using the webUI # tests/acceptance/stepDefinitions/loginContext.js:67
   ✔ And the user has browsed to the files page # tests/acceptance/stepDefinitions/filesContext.js:82
   ✔ And user "user0" has uploaded file with content "lorem content" to "lorem.txt" # tests/acceptance/stepDefinitions/filesContext.js:92
   ✔ And user "user0" has uploaded file with content "new lorem content" to "lorem.txt" # tests/acceptance/stepDefinitions/filesContext.js:92
   ✔ When the user browses to display the "versions" details of file "lorem.txt" # tests/acceptance/stepDefinitions/filesContext.js:112
   ✔ Then the content of file "lorem.txt" for user "user0" should be "new lorem content" # tests/acceptance/stepDefinitions/filesContext.js:482
   ✖ And the versions list should contain 2 entries # tests/acceptance/stepDefinitions/filesContext.js:458
       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

       2 !== 1

           + expected - actual

           -2
           +1

           at _callee20$ (/srv/app/phoenix/tests/acceptance/stepDefinitions/filesContext.js:460:17)
           at tryCatch (/srv/app/phoenix/node_modules/regenerator-runtime/runtime.js:63:40)
           at Generator.invoke [as _invoke] (/srv/app/phoenix/node_modules/regenerator-runtime/runtime.js:293:22)
           at Generator.next (/srv/app/phoenix/node_modules/regenerator-runtime/runtime.js:118:21)
           at asyncGeneratorStep (/srv/app/phoenix/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
           at _next (/srv/app/phoenix/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
           at processTicksAndRejections (internal/process/task_queues.js:86:5)
   ✔ After # tests/acceptance/stepDefinitions/provisioningContext.js:226
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:285
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:258
   ✔ After # tests/acceptance/setup.js:110
   ✔ After # tests/acceptance/setup.js:106
   ✔ After # tests/acceptance/setup.js:102
   ✔ After # tests/acceptance/setup.js:95
   ✔ After # tests/acceptance/setup.js:86
   ✔ After # tests/acceptance/setup.js:54
```

It usually passes. I am suspicious that there might be a timing problem - the 2 uploads are done using WebDav. The content of the file is the 2nd-uploaded content, so that is good. Maybe there is an issue with doing the uploads too close together. I know that in core test code we space these kinds of steps out 1 second apart to avoid known issues (features) about Unix timestamps that have only 1-second resolution.

Is there something that we should do in the test code to avoid known close-together-in-time version issues?

**Comment by individual-it** [comment]
hmm, there is already a wait between the uploads https://github.com/owncloud/phoenix/blob/a082cab8ffa1bff61179bd4ee544ac95c767de78/tests/acceptance/stepDefinitions/filesContext.js#L97

**Comment by individual-it** [comment]
I managed to make it fail locally, now need to find out if it just a waiting issue or does the server really only return one item

**Comment by individual-it** [comment]
looks like ocis really only returns a single element
```


<?xml version="1.0" encoding="UTF-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
   <d:response>
      <d:href>/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjBiZGRhZjc3LTMzNjEtNGRkNS04MzMyLTk4MThiNzg2Y2M5MA==/v/</d:href>
      <d:propstat>
         <d:prop>
            <oc:id>dmlydHVhbDptZXRhL01USTROR1F5TXpndFlXRTVNaTAwTW1ObExXSmtZelF0TUdJd01EQXdNREE1TVRVM09qQmlaR1JoWmpjM0xUTXpOakV0TkdSa05TMDRNek15TFRrNE1UaGlOemcyWTJNNU1BPT0vdg==</oc:id>
            <oc:fileid>dmlydHVhbDptZXRhL01USTROR1F5TXpndFlXRTVNaTAwTW1ObExXSmtZelF0TUdJd01EQXdNREE1TVRVM09qQmlaR1JoWmpjM0xUTXpOakV0TkdSa05TMDRNek15TFRrNE1UaGlOemcyWTJNNU1BPT0vdg==</oc:fileid>
            <d:getetag>"187fd5d9c73692ed1e64ca36390f2e2e"</d:getetag>
            <d:resourcetype>
               <d:collection />
            </d:resourcetype>
            <d:getcontenttype>httpd/unix-directory</d:getcontenttype>
            <oc:size>0</oc:size>
            <d:getlastmodified>Wed, 18 Nov 2020 07:43:35 +0000</d:getlastmodified>
            <oc:favorite>0</oc:favorite>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
   <d:response>
      <d:href>/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjBiZGRhZjc3LTMzNjEtNGRkNS04MzMyLTk4MThiNzg2Y2M5MA==/v/1605685415</d:href>
      <d:propstat>
         <d:prop>
            <oc:id>dmVyc2lvbnM6MGJkZGFmNzctMzM2MS00ZGQ1LTgzMzItOTgxOGI3ODZjYzkwQDE2MDU2ODU0MTU=</oc:id>
            <oc:fileid>dmVyc2lvbnM6MGJkZGFmNzctMzM2MS00ZGQ1LTgzMzItOTgxOGI3ODZjYzkwQDE2MDU2ODU0MTU=</oc:fileid>
            <d:getcontentlength>13</d:getcontentlength>
            <d:getlastmodified>Wed, 18 Nov 2020 07:43:35 +0000</d:getlastmodified>
            <oc:favorite>0</oc:favorite>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
</d:multistatus>

```

vs. a response when the test pass:
```
<?xml version="1.0" encoding="UTF-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
   <d:response>
      <d:href>/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3Ojg2OTlmZjdmLTc0YzgtNDdkZC1iNTFiLTAyNTM0YzQxNzI2MA==/v/</d:href>
      <d:propstat>
         <d:prop>
            <oc:id>dmlydHVhbDptZXRhL01USTROR1F5TXpndFlXRTVNaTAwTW1ObExXSmtZelF0TUdJd01EQXdNREE1TVRVM09qZzJPVGxtWmpkbUxUYzBZemd0TkRka1pDMWlOVEZpTFRBeU5UTTBZelF4TnpJMk1BPT0vdg==</oc:id>
            <oc:fileid>dmlydHVhbDptZXRhL01USTROR1F5TXpndFlXRTVNaTAwTW1ObExXSmtZelF0TUdJd01EQXdNREE1TVRVM09qZzJPVGxtWmpkbUxUYzBZemd0TkRka1pDMWlOVEZpTFRBeU5UTTBZelF4TnpJMk1BPT0vdg==</oc:fileid>
            <d:getetag>"5022394e4bc564b87120cced650035bf"</d:getetag>
            <d:resourcetype>
               <d:collection />
            </d:resourcetype>
            <d:getcontenttype>httpd/unix-directory</d:getcontenttype>
            <oc:size>0</oc:size>
            <d:getlastmodified>Wed, 18 Nov 2020 07:43:03 +0000</d:getlastmodified>
            <oc:favorite>0</oc:favorite>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
   <d:response>
      <d:href>/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3Ojg2OTlmZjdmLTc0YzgtNDdkZC1iNTFiLTAyNTM0YzQxNzI2MA==/v/1605685382</d:href>
      <d:propstat>
         <d:prop>
            <oc:id>dmVyc2lvbnM6ODY5OWZmN2YtNzRjOC00N2RkLWI1MWItMDI1MzRjNDE3MjYwQDE2MDU2ODUzODI=</oc:id>
            <oc:fileid>dmVyc2lvbnM6ODY5OWZmN2YtNzRjOC00N2RkLWI1MWItMDI1MzRjNDE3MjYwQDE2MDU2ODUzODI=</oc:fileid>
            <d:getcontentlength>446</d:getcontentlength>
            <d:getlastmodified>Wed, 18 Nov 2020 07:43:02 +0000</d:getlastmodified>
            <oc:favorite>0</oc:favorite>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
   <d:response>
      <d:href>/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3Ojg2OTlmZjdmLTc0YzgtNDdkZC1iNTFiLTAyNTM0YzQxNzI2MA==/v/1605685383</d:href>
      <d:propstat>
         <d:prop>
            <oc:id>dmVyc2lvbnM6ODY5OWZmN2YtNzRjOC00N2RkLWI1MWItMDI1MzRjNDE3MjYwQDE2MDU2ODUzODM=</oc:id>
            <oc:fileid>dmVyc2lvbnM6ODY5OWZmN2YtNzRjOC00N2RkLWI1MWItMDI1MzRjNDE3MjYwQDE2MDU2ODUzODM=</oc:fileid>
            <d:getcontentlength>13</d:getcontentlength>
            <d:getlastmodified>Wed, 18 Nov 2020 07:43:03 +0000</d:getlastmodified>
            <oc:favorite>0</oc:favorite>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
</d:multistatus>

**Comment by individual-it** [comment]
even there is some waiting before an upload the logic has an issue
the waiting is called before the upload in https://github.com/owncloud/phoenix/blob/034efba13d429b26b2cad7562d928866dfc84fe8/tests/acceptance/stepDefinitions/filesContext.js#L97
inside of that function `timeOfLastUploadOperation` is set https://github.com/owncloud/phoenix/blob/034efba13d429b26b2cad7562d928866dfc84fe8/tests/acceptance/stepDefinitions/filesContext.js#L229 but the upload hasn't even started, so if the upload is slow the waiting will be too short in the next upload
